#pragma once
#include "Chunk.h"
#include "Shader.h"
#include "ThreadPool.h"
#include "WorldGenerator.h"
#include <glm/glm.hpp>
#include <memory>
#include <mutex>
#include <queue>
#include <unordered_map>

// A custom hashing struct so we can use std::pair<int, int> as keys in our unordered_map
struct ChunkCoordinateHash {
    std::size_t operator()(const std::pair<int, int>& k) const {
        return std::hash<int>()(k.first) ^ (std::hash<int>()(k.second) << 1);
    }
};

class ChunkManager {
public:
    ChunkManager(ThreadPool& pool);

    // Checks camera position and manages chunk lifecycle
    void Update(glm::vec3 cameraPosition);

    // Renders all active chunks
    void Render(Shader& shader, const glm::mat4& viewProj);

private:
    ThreadPool& threadPool;
    WorldGenerator generator;

    // Render distance (e.g., 4 chunks in every direction from the camera)
    int renderDistance = 4;

    // The main storage for chunks currently in the world
    std::unordered_map<std::pair<int, int>, std::shared_ptr<Chunk>, ChunkCoordinateHash>
        activeChunks;

    // Tracks chunks currently being generated by the ThreadPool so we don't spawn duplicates
    std::unordered_map<std::pair<int, int>, bool, ChunkCoordinateHash> generatingChunks;

    // --- Thread-Safe Handoff ---
    std::mutex handoffMutex;
    // A queue containing the coordinates and the finished chunk pointer
    std::queue<std::pair<std::pair<int, int>, std::shared_ptr<Chunk>>> handoffQueue;
};